services:
  mongodb:
    image: mongo:latest
    networks:
      - network-services
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  database-initializer:
    build:
      context: ./database-initializer/
      network: host
    networks:
      - network-services
    environment:
      - URI=${URI_DATABASE_ROOT}
      - DB_NAME=${DB_NAME}

      - USER_COLLECTION=${USER_COLLECTION}
      - TOKEN_COLLECTION=${TOKEN_COLLECTION}
      - CONVERSATION_COLLECTION=${CONVERSATION_COLLECTION}
      - MESSAGE_COLLECTION=${MESSAGE_COLLECTION}

      - MONGO_USER_USERNAME=${MONGO_USER_USERNAME}
      - MONGO_USER_PWD=${MONGO_USER_PWD}
      - MONGO_CHAT_USERNAME=${MONGO_CHAT_USERNAME}
      - MONGO_CHAT_PWD=${MONGO_CHAT_PWD}
    depends_on:
      mongodb:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
      network: host
    networks:
      - network-services
    environment:
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - URI=${URI_DATABASE_USER_SERVICE}

      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}

      - USER_COLLECTION=${USER_COLLECTION}
      - TOKEN_COLLECTION=${TOKEN_COLLECTION}

      - DB_NAME=${DB_NAME}
      - UTILS_API=${UTILS_API}
      - USER_API=${USER_API}
    expose:
      - "8003"
    depends_on:
      database-initializer:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8003/api/user/health" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  game-service:
    build:
      context: ./game-service/
      network: host
    networks:
      - network-services
    expose:
      - "8002"
    environment:
      - GATEWAY_URL=${GATEWAY_URL}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8002/health" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  chat-service:
    build:
      context: .
      dockerfile: chat-service/Dockerfile
      network: host
    networks:
      - network-services
    expose:
      - "8005"
    environment:
      - DB_NAME=${DB_NAME}
      - URI=${URI_DATABASE_CHAT_SERVICE}
      - GATEWAY_URL=${GATEWAY_URL}
      - CHAT_SERVICE_URL=${CHAT_SERVICE_URL}

      - USER_COLLECTION=${USER_COLLECTION}
      - CONVERSATION_COLLECTION=${CONVERSATION_COLLECTION}
      - MESSAGE_COLLECTION=${MESSAGE_COLLECTION}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8005/api/user/health" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  files:
    build:
      context: ./files/
      network: host
      target: prod
    networks:
      - network-services
    expose:
      - "8001"
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8001/health" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  gateway:
    build:
      context: ./gateway/
      network: host
    networks:
      - network-services
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - GAME_SERVICE_URL=${GAME_SERVICE_URL}
      - CHAT_SERVICE_URL=${CHAT_SERVICE_URL}
      - FILES_URL=${FILES_URL}
      - GATEWAY_URL=${GATEWAY_URL}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - DOC_API_SERVICE_URL=${DOC_API_SERVICE_URL}
    depends_on:
      game-service:
        condition: service_healthy
      doc-api:
        condition: service_completed_successfully

  doc-api:
    build:
      context: ./documentation-api/
      network: host
    networks:
      - network-services
    expose:
      - "8004"
    environment:
      - SERVICES_URL=${USER_SERVICE_URL}/api/user
      - DOC_API_SERVICE_URL=${DOC_API_SERVICE_URL}
      - FILES_URL=${FILES_URL}
    depends_on:
      files:
        condition: service_healthy
      user-service:
        condition: service_healthy

networks:
  network-services:
    driver: bridge

volumes:
  mongo-data: