const DATABASE_ERRORS = Object.freeze({
    CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
    MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
    PARTICIPANT_NOT_FOUND: "PARTICIPANT_NOT_FOUND",
    VALIDATION_FAILED: "VALIDATION_FAILED"
});

module.exports = {DATABASE_ERRORS};