const DATABASE_ERRORS = Object.freeze({
    CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
    PARTICIPANT_NOT_FOUND: "PARTICIPANT_NOT_FOUND",
    USER_NOT_PARTICIPANT: "USER_NOT_PARTICIPANT",
    VALIDATION_FAILED: "VALIDATION_FAILED"
});

module.exports = {DATABASE_ERRORS};